server:
  port: 3001

spring:
  profiles:
    active: dev

  # 데이터 베이스 연결 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:myoracle
    username: PROJECT_BE
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행되는 쿼리 콘솔 출력
        format_sql: true # 콘솔 창에 출력되는 쿼리를 가독성 좋게 포매팅
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect  # DB툴에 맞게 쿼리를 자동으로 바꿔줌
    hibernate:
      ddlAuto: create #update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# JSON WebToken 설정
jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM # base64 인코딩 (a~z로 만듦)
  accessTokenValidityInSeconds: 3600 # 토큰의 유효시간 60 min
